### ISSUE TITLE
The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'

### ISSUE THREAD

**Issue by theochampion** [renefloor/flutter_cached_network_image#207]
After updating flutter to `Channel stable, v1.7.8+hotfix.3` I get this error at compilation due to an API breaking change.

```bash
Compiler message:
file:///Users/theo/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-0.4.2/lib/cached_network_i
mage.dart:199:38: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the
parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart'
 ('file:///Users/theo/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart'
 ('file:///Users/theo/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
      oldImageStream?.removeListener(_handleImageChanged);
```

Any ETA on this? (Happy to help if necessary ;) )

**Comment by oh-jy** [comment]
me too

**Comment by debottam31** [comment]
@renefloor please look into this issue, bit urgent. Happy to help

**Comment by renefloor** [comment]
You are using version 0.4.2, this has already been fixed in newer versions...

**Comment by oh-jy** [comment]
I have tried to update this plugin to the newest version , but it still doesn't work..... I'm using  flutter Channel stable, v1.7.8+hotfix.3

**Comment by RainAndRain** [comment]
I have tried to update this plugin to the newest version  1.1.1 , but it still doesn't work..... I'm using flutter Channel stable, v1.7.8+hotfix.3

**Comment by oh-jy** [comment]
> I have tried to update this plugin to the newest version 1.1.1 , but it still doesn't work..... I'm using flutter Channel stable, v1.7.8+hotfix.3

em......... make sure your plugin  is the newest version in the  [ .pub-cache\hosted] folder,then i find it works.

**Comment by RainAndRain** [comment]
> > 我试图将此插件更新到最新版本1.1.1，但它仍然无效.....我正在使用flutter Channel stable，v1.7.8 + hotfix.3
> 
> em .........确保你的插件是[.pub-cache \ hosted]文件夹中的最新版本，然后我发现它有效。

Definitely, I have deleted other versions and only retained version 1.1.1  ，but it still doesn't work.....

**Comment by msngithub** [comment]
just add (context, url) => after placeholder like this

`new CachedNetworkImage(
              imageUrl: yourUrl,
              placeholder:(context, url) => new Image(
                image: AssetImage("assets/images/placeholder-image.png"),
              ),
            )`
