### ISSUE TITLE
How to reload image from cache

### ISSUE THREAD

**Issue by FilipeOS** [renefloor/flutter_cached_network_image#208]
Hi,

I have a user profile, I change the image BUT how can I refresh that user photo url so it can get the new one?

Thank you

**Comment by jrnelson333** [comment]
One solution would be to use a new URL for a new image. In my opinion that is the correct solution. If a user changes their profile picture, I would consider that to be a new resource. Because it is is a new resource, I think it should have a new resource locator (i.e. new URI).

**Comment by jlnr** [comment]
That depends on how the API was designed. In my case, the image URL is always `/users/123/avatar`, just like my user is always `/users/123`. I can update both resources, but their URLs stay the same.

Either way, changing the backend is not feasible right now, it would be good if clearing the cache had an effect :)

**Comment by renefloor** [comment]
You can clear the cached image by calling on the cachemanager directly, but for that you have to know when the image changes. You can call DefaultCacheManager().removeFile(url)

See https://pub.dev/documentation/flutter_cache_manager/latest/flutter_cache_manager/DefaultCacheManager-class.html

**Comment by jlnr** [comment]
It called `emptyCache()` to clear everything but the CircleAvatar didn't reload from the CachedNetworkImageProvider even when I changed the avatar's key. I'll try using a CachedImageWidget later. How these things work together could be useful information to have in the README.

**Comment by FilipeOS** [comment]
`DefaultCacheManager().removeFile(photoUrl);` don't work, don't know what is `DefaultCacheManager()`

Am I missing some import?

**Comment by jlnr** [comment]
@FilipeOS If you add `flutter_cache_manager` to your pubspec, Android Studio will let you automatically import it.

**Comment by FilipeOS** [comment]
@jlnr sorry but why should I import if I have `cached_network_image` on pubspec already?

**Comment by renefloor** [comment]
There was something wrong in the link between the cache manager and the image widget. Because of that images already in memory were not refreshed. Should be fixed in the latest release, if not please re-open this issue.

**Comment by dshukertjr** [comment]
I am using  
```
cached_network_image: ^2.0.0
flutter_cache_manager: ^1.1.3
```
and still cannot get the cache to be deleted. I even tried 
`DefaultCacheManager().emptyCache();`
but still get the old image. 

What could I be doing wrong?
