### ISSUE TITLE
Image not updating in ListView

### ISSUE THREAD

**Issue by p30arena** [renefloor/flutter_cached_network_image#31]
Image not updating in ListView

https://youtu.be/W7OSeqWZZjA

_

**Comment by renefloor** [comment]
I think that it's the same issue as #16. I think I will fix that soon.

**Comment by p30arena** [comment]
@renefloor our app is ready for presentation, just this tiny issue.
Thanks.

**Comment by renefloor** [comment]
This should be fixed now in 0.4.0

**Comment by luishar0** [comment]
I updated the package to 0.4.0 and things look the same. 
ListView show correctly the first time. 
Then if you rebuild with new data, all the data changes correctly except for the images. 
If the previos ListView had 2 rows, the next time, those 2 rows will be wrong. 

Any hints for a work around? 

Regards. 

![screen shot 2018-04-14 at 1 34 42 pm](https://user-images.githubusercontent.com/35408969/38771418-c6a5f4a0-3fe8-11e8-8edb-9f19434e1fb4.png)
![screen shot 2018-04-14 at 1 35 04 pm](https://user-images.githubusercontent.com/35408969/38771419-c6bb4efe-3fe8-11e8-8c29-5a56f9080117.png)

**Comment by renefloor** [comment]
Yes I found out through issue #34 that it is still not working as it should be. I'll have a look at it. Does it only go wrong when updating data or also when scrolling? How do you update the data? Do you pull data from an api and then set a variable with setState?

**Comment by p30arena** [comment]
@renefloor 

```
new StreamBuilder<List<Product>>(
                stream: _yabcoCentralShop.getProductsListStream(),
                builder: (BuildContext context,
                    AsyncSnapshot<List<Product>> snapshot) {
                  if (snapshot.hasError) {
                    print(snapshot.error);
                    return Smart.getText(context, 'خطا در اتصال به شبکه');
                  }
                  switch (snapshot.connectionState) {
                    case ConnectionState.active:
                      return renderProducts(snapshot.data);
                    default:
                      return new Center(
                        child: new CircularProgressIndicator(),
                      );
                  }
                },
              ),
```


and


```
Widget renderProducts(List<Product> productsList) {
    int showMoreLastIndex = productsList.length;

    return new ListView.builder(
      padding: new EdgeInsets.all(16.0),
      itemCount: _showMore ? productsList.length + 1 : productsList.length,
      itemExtent: 100.0,
      itemBuilder: (context, index) {
        if (_showMore && index == showMoreLastIndex) {
          return new Center(
            child: new FractionallySizedBox(
              heightFactor: 0.5,
              widthFactor: 1.0,
              child: new RaisedButton(
                color: Colors.lightBlueAccent,
                child: Smart.getText(
                  context,
                  'بیشتر',
                  textStyle: Smart.getTextStyle(
                      context, new TextStyle(color: Colors.white)),
                ),
                onPressed: () {
                  _page++;
                  return load(
                    clearHistory: false,
                  );
                },
              ),
            ),
          );
        }

        Product prod = productsList[index];

        return new Card(
          child: new InkWell(
            onTap: () {
              Navigator.of(context).push(
                    new MaterialPageRoute(
                      builder: (context) => Smart.getDirectionality(
                            new ProductPage(
                              product: prod,
                            ),
                          ),
                    ),
                  );
            },
            child: new Row(
              children: <Widget>[
                new SizedBox(
                  width: 100.0,
                  height: 100.0,
                  child: NetImage(getCDNUrlForFileId(prod.imageId)),
                ),
                new Expanded(
                  child: new Padding(
                    padding: new EdgeInsets.only(
                      right: 16.0,
                      left: 16.0,
                    ),
                    child: new Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: <Widget>[
                        Smart.getText(context, prod.title),
                        Smart.getText(
                          context,
                          prod.price,
                          textStyle: Smart.getTextStyle(
                            context,
                            new TextStyle(
                              color: Colors.green[700],
                              fontSize: 19.0,
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),
        );
      },
    );
  }
```

**Comment by luishar0** [comment]
Not sure what happened but it's working now for me as well. 

Thank you! :)
