### ISSUE TITLE
Does not update image in gridview

### ISSUE THREAD

**Issue by neckaros** [renefloor/flutter_cached_network_image#34]
Hello,

If i use CachedNetworkImage in a grid view and the content changes the images does not get updated (the footer title is updated correctly)
```
return new GridView.count(
              crossAxisCount: (orientation == Orientation.portrait) ? 3 : 6,
              childAspectRatio: 0.7,
              padding: const EdgeInsets.all(4.0),
              mainAxisSpacing: 4.0,
              crossAxisSpacing: 4.0,
              children: movies.map((var movie) {
                return new GridTile(
                    footer: new Text(movie.title),
                    child: new GestureDetector(
                        onTap: () => Navigator.of(context).push(
                                new MaterialPageRoute(
                                    builder: (BuildContext context) => new MovieDetailPage(movie)
                            )
                            ),
                        child: new CachedNetworkImage(
                            imageUrl: MoviesService.getImagePath(movie.id),
                            fit: BoxFit.cover,
                            placeholder: new Container(color: Colors.black12),
                            errorWidget: new Icon(Icons.error),
                        ),             
                       ));
              }).toList(),
            );
```
if i use a FadeInImage it works correctly:
```
...
child: new FadeInImage.memoryNetwork(
                        fit: BoxFit.cover,
                      placeholder: kTransparentImage,
                      image:
                          MoviesService.getImagePath(movie.id),
                    )
...
```
I'm using latest version

**Comment by renefloor** [comment]
Are you using version 0.4.0 I published today? I thought that should have fixed that..
Could you give me an example I can directly test?

**Comment by neckaros** [comment]
Maybe i was to fast in saying latest! did update early this morning european time. Will try again and revert back to you :)

**Comment by neckaros** [comment]
I still have the issue with: ".pub-cache\hosted\pub.dartlang.org\cached_network_image-0.4.0\lib\cached_network_image.dart"

**Comment by renefloor** [comment]
I'll try to find what's going wrong

**Comment by neckaros** [comment]
Using the library as an image provider work tho:

```
child: new FadeInImage(
                        image: new CachedNetworkImageProvider(MoviesService.getImagePath(movie.id)),
                        fit: BoxFit.cover,
                      placeholder: new MemoryImage(kTransparentImage)     
                    )
```

**Comment by renefloor** [comment]
Yes, I expect something with didChangeDependencies or didUpdateWidget or something. I am not completely aware how they should work yet.
